"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['pdftest.py']
DATA_FILES = ['/Users/samralston/Desktop/print/VERDANA.TTF','/Users/samralston/Desktop/print/day.pdf','destination.pdf']
OPTIONS = {'packages':['reportlab.pdfgen','reportlab.lib.pagesizes','reportlab.pdfbase.ttfonts','reportlab.pdfbase']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
